server:
  port: 8083

spring:
  application:
    name: cms-config
  cloud:
      config:
        server:
          git:
            uri: https://gitee.com/bobi1234/config-repo
            basedir: D:\basedir
# 私密仓库才需要账号密码
#            username: bobi1234
#            password: ********

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
